import pytest

from src.api import ArgumentsField, CharField, EmailField, Field, PhoneField

fields_positive_fixtures = [
    pytest.param(
        Field,
        {"required": True, "nullable": True},
        "test_value",
        id='Field: required=True, nullable=True, value="test_value"',
    ),
    pytest.param(
        Field,
        {"required": False, "nullable": True},
        "test_value",
        id='Field: required=False, nullable=True, value="test_value"',
    ),
    pytest.param(
        Field,
        {"required": True, "nullable": False},
        "test_value",
        id='Field: required=True, nullable=False, value="test_value"',
    ),
    pytest.param(
        Field,
        {"required": False, "nullable": False},
        "test_value",
        id='Field: required=False, nullable=False, value="test_value"',
    ),
    pytest.param(
        CharField,
        {"required": True, "nullable": False},
        "char_test_value",
        id="CharField: value is str",
    ),
    pytest.param(
        ArgumentsField,
        {"required": True, "nullable": False},
        {"key1": "value1", "key2": "value2"},
        id="ArgumentsField: value is dict",
    ),
    pytest.param(
        EmailField,
        {"required": True, "nullable": False},
        "test@test.com",
        id="EmailField: value is test@test.com",
    ),
    pytest.param(
        PhoneField,
        {"required": True, "nullable": False},
        "79998887766",
        id='PhoneField: value is "79998887766"',
    ),
    pytest.param(
        PhoneField,
        {"required": True, "nullable": False},
        79998887766,
        id="PhoneField: value is 79998887766 (int)",
    ),
]


fields_negative_fixtures = [
    pytest.param(
        Field,
        {"required": True, "nullable": False},
        None,
        "{field_name} is required",
        id="Field: required=True, nullable=False, value=None",
    ),
    pytest.param(
        Field,
        {"required": True, "nullable": False},
        "",
        "{field_name} isn't nullable",
        id='Field: required=True, nullable=False, value=""',
    ),
    pytest.param(
        Field,
        {"required": True, "nullable": False},
        (),
        "{field_name} isn't nullable",
        id="Field: required=True, nullable=False, value=()",
    ),
    pytest.param(
        Field,
        {"required": True, "nullable": False},
        {},
        "{field_name} isn't nullable",
        id="Field: required=True, nullable=False, value={}",
    ),
    pytest.param(
        Field,
        {"required": True, "nullable": False},
        [],
        "{field_name} isn't nullable",
        id="Field: required=True, nullable=False, value=[]",
    ),
    pytest.param(
        CharField,
        {"required": True, "nullable": False},
        1,
        "{field_name} must be a string",
        id="CharField: value is int",
    ),
    pytest.param(
        CharField,
        {"required": True, "nullable": False},
        1.0,
        "{field_name} must be a string",
        id="CharField: value is float",
    ),
    pytest.param(
        CharField,
        {"required": True, "nullable": False},
        True,
        "{field_name} must be a string",
        id="CharField: value is bool",
    ),
    pytest.param(
        CharField,
        {"required": True, "nullable": False},
        ["one", "two"],
        "{field_name} must be a string",
        id="CharField: value is list",
    ),
    pytest.param(
        CharField,
        {"required": True, "nullable": False},
        {"key1": "value1", "key2": "value2"},
        "{field_name} must be a string",
        id="CharField: value is dict",
    ),
    pytest.param(
        ArgumentsField,
        {"required": True, "nullable": False},
        "test_value",
        "{field_name} must be a dictionary",
        id="ArgumentsField: value is str",
    ),
    pytest.param(
        ArgumentsField,
        {"required": True, "nullable": False},
        1,
        "{field_name} must be a dictionary",
        id="ArgumentsField: value is int",
    ),
    pytest.param(
        ArgumentsField,
        {"required": True, "nullable": False},
        1.0,
        "{field_name} must be a dictionary",
        id="ArgumentsField: value is float",
    ),
    pytest.param(
        ArgumentsField,
        {"required": True, "nullable": False},
        True,
        "{field_name} must be a dictionary",
        id="ArgumentsField: value is bool",
    ),
    pytest.param(
        ArgumentsField,
        {"required": True, "nullable": False},
        ["one", "two"],
        "{field_name} must be a dictionary",
        id="ArgumentsField: value is list",
    ),
    pytest.param(
        EmailField,
        {"required": True, "nullable": False},
        "test@test",
        "{field_name} must be email",
        id="EmailField: value is test@test",
    ),
    pytest.param(
        EmailField,
        {"required": True, "nullable": False},
        "test.com",
        "{field_name} must be email",
        id="EmailField: value is test.com",
    ),
    pytest.param(
        EmailField,
        {"required": True, "nullable": False},
        "test",
        "{field_name} must be email",
        id="EmailField: value is test",
    ),
    pytest.param(
        PhoneField,
        {"required": True, "nullable": False},
        "89998887766",
        '{field_name} must starts with "7" and be no longer than 11 characters',
        id='PhoneField: value is "89998887766"',
    ),
    pytest.param(
        PhoneField,
        {"required": True, "nullable": False},
        "+7-999-888-77-66",
        '{field_name} must starts with "7" and be no longer than 11 characters',
        id='PhoneField: value is "+7-999-888-77-66"',
    ),
    pytest.param(
        PhoneField,
        {"required": True, "nullable": False},
        "8999888",
        '{field_name} must starts with "7" and be no longer than 11 characters',
        id='PhoneField: value is "8999888"',
    ),
    pytest.param(
        PhoneField,
        {"required": True, "nullable": False},
        89998887766,
        '{field_name} must starts with "7" and be no longer than 11 characters',
        id="PhoneField: value is 89998887766 (int)",
    ),
    pytest.param(
        PhoneField,
        {"required": True, "nullable": False},
        8999888.0000,
        "{field_name} must be number or string",
        id="PhoneField: value is 8999888.0000 (float)",
    ),
]
